### ISSUE TITLE
blurry images

### ISSUE THREAD

**Issue by izenn** [ledowong/padopt#3] opened 2016-04-10 23:39 UTC
the images on the grid are blurry.  it is almost like they are scaled up from being small rather than being scaled down from a larger size

**Comment by ledowong** [comment] 2016-04-11 00:02
yea, it is because now the orb is draw inside canvas with fixed size (but scaled a little bit), and then the board itself is scaled with css 100% width to make it responsive. (The old one is totally not working in mobile....)
So it is a trade off for responsive design. There maybe a better solution, please let me know if u found one.

**Comment by izenn** [comment] 2016-04-11 01:27
i'm working on it.  i'll send a commit if i find something

**Comment by izenn** [comment] 2016-04-11 11:41
what about using http://responsejs.com/ and getting rid of the css? otherwise, i've been experimenting with images that are 100x100 and   var _ORB_SIZE = 52;   var _GRID_SIZE = 50; and it is better, but still not clear as compared to https://izenn.github.io/padopt-legacy/index.html

**Comment by ledowong** [comment] 2016-04-11 12:21
In old code, orbs, path and moving dot, are 3 different layers. To make them overlap each others in the correct position, CSS fixed position and fixed width is needed. That's why the old design is not responsive (not re-sizable base on browser window width)

Now in this fork, all above 3 things are drawing inside a single HTML5 canvas, so all we need is re-size this single canvas HTML node, and there are two way to achieve this (in my knowledge):
1. re-size the canvas actual width and height when browser window re-size;
2. just like an image, use CSS to set width: 100% so it auto scale;

Currently I am using solution 2, coz it is easier. For solution 1, there is A LOT of math need to do to calculate orbs size, board size, path length, line width, everything. And it also does scale the orbs image (just scale by canvas, not CSS), it most likely will blur too....

The CSS breakpoint is take care by Bootstrap grid system. We don't need to deal with that at all.

When I writing this reply, I realized that the root cause is the orbs image is not vector image, so it must blur when re-size.

**Comment by izenn** [comment] 2016-04-11 12:22
i pushed a commit that clears up the images quite significantly -- if you could check it over to see what you think: https://github.com/izenn/padopt/commit/d69c7d52975ebd39c9dcb5cf8e05357b54da432d

the code is messy, but i wanted to leave some remnants in so i can revert some of the draw orb changes

also, you can test here: https://izenn.github.io/padopt/index.html

I'll try to convert the images to SVG today

**Comment by ledowong** [comment] 2016-04-11 16:17
I guess SVG does help the scaling inside canvas (orb draw on canvas), but after that, canvas itself is not a vector image (just CSS width 100%), so it still blur when re-size base on breakpoint, lol....

I don't think it is that important, it still works great right now.

For the commit, I will check later tonight. Git diff not working due to long dataURI...

**Comment by ledowong** [comment] 2016-04-11 20:01
your one look nice. I just extract the source image form .apk, with higher resolutions. I am going to replace with those and try to write a better code for orb data array.

**Comment by izenn** [comment] 2016-04-11 20:33
where in the APK were they -- i looked last night but didn't see them

**Comment by ledowong** [comment] 2016-04-11 20:51
no idea, I just use [this](https://github.com/codywatts/Puzzle-and-Dragons-Texture-Tool).

I committed. Now I don't scale the image when I draw it on canvas (just use the original size). The code will auto adjust the 'center' of the orb, due to orbs are come with different sizes (heart, junk, poison is smaller).

Its look good now. https://github.com/ledowong/padopt/commit/0a64f9ac19820ac6527e0b1dd7e633531636bf14

**Closed as completed** 2016-04-11 20:52 UTC
Labels: enhancement
